services:
  database:
    image: mysql:9.1
    container_name: todo-database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=todo_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-database:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - todo-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: todo-api
    ports:
      - "8080:8080"
    networks:
      - todo-network
    depends_on:
      - database
    

volumes:
  mysql-database:

networks:
  todo-network: